const key='noirBarberData';const defaultData={brand:'NOIR',logo:'',heroText:'Не просто стрижка. Чёткая форма, чистая линия и городской характер.',spaceText:'Тёмное пространство, металл, зеркала и свет, который подчёркивает форму. Никакой случайности — только характер.',footerText:'Barber shop for people who care about the details.',address:'ул. Стильная, 14',phone:'+7 900 000 00 00',services:[{id:1,name:'Мужская стрижка',desc:'Ножницы + машинка, мойка и финальная укладка.',price:1800},{id:2,name:'Стрижка под машинку',desc:'Чистая короткая форма без лишнего.',price:1200},{id:3,name:'Fade / Taper',desc:'Плавный переход, контур и укладка.',price:2000},{id:4,name:'Борода',desc:'Моделирование, горячее полотенце и уход.',price:1100},{id:5,name:'Стрижка + борода',desc:'Полный образ в одном визите.',price:2700},{id:6,name:'Камуфляж седины',desc:'Мягкое тонирование без эффекта окрашивания.',price:1500}]};
const get=()=>{try{return {...defaultData,...(JSON.parse(localStorage.getItem(key))||{})}}catch{return structuredClone(defaultData)}};let data=get();const $=id=>document.getElementById(id);const toast=msg=>{$('toast').textContent=msg;$('toast').classList.add('show');setTimeout(()=>$('toast').classList.remove('show'),2500)};
function renderContent(){['brand','phone','address','heroText','spaceText','footerText'].forEach(k=>$(k).value=data[k]||'');renderLogoPreview()}
function renderLogoPreview(){const box=$('logoPreview');box.innerHTML=data.logo?`<img src="${data.logo}" alt="Предпросмотр логотипа">`:'<span>Сейчас используется текстовый логотип</span>'}
function renderServices(){$('serviceEditor').innerHTML=data.services.map((s,i)=>`<div class="service-row" data-id="${s.id}"><span class="num">${String(i+1).padStart(2,'0')}</span><input class="s-name" value="${esc(s.name)}"><input class="s-desc" value="${esc(s.desc)}"><input class="s-price" type="number" value="${s.price}"><button class="delete">×</button></div>`).join('');document.querySelectorAll('.delete').forEach(b=>b.onclick=()=>{const id=Number(b.parentElement.dataset.id);data.services=data.services.filter(s=>s.id!==id);persist();renderServices()})}
function renderBookings(){const list=JSON.parse(localStorage.getItem('noirBookings')||'[]');$('badge').textContent=list.filter(x=>x.status==='new').length||'';$('bookingList').innerHTML=list.length?list.map(b=>{const s=data.services.find(x=>String(x.id)===String(b.serviceId));return `<article class="booking-card ${b.status==='new'?'new':''}"><div><h3>${esc(b.name)} — ${esc(s?.name||'Услуга')}</h3><p>${esc(b.phone)} · ${esc(b.comment||'Без комментария')}</p><p><button data-read="${b.id}">${b.status==='new'?'Отметить прочитанной':'Прочитано'}</button></p></div><div class="when">${esc(b.date)}<br>${esc(b.time)}</div></article>`}).join(''):'<div class="empty">Пока тихо. Новые записи появятся здесь.</div>';document.querySelectorAll('[data-read]').forEach(btn=>btn.onclick=()=>{const arr=JSON.parse(localStorage.getItem('noirBookings')||'[]');const x=arr.find(a=>a.id==btn.dataset.read);if(x)x.status='read';localStorage.setItem('noirBookings',JSON.stringify(arr));renderBookings()})}
function persist(){localStorage.setItem(key,JSON.stringify(data));toast('Изменения сохранены')};function esc(s){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#039;','"':'&quot;'}[c]))}
$('saveContent').onclick=()=>{['brand','phone','address','heroText','spaceText','footerText'].forEach(k=>data[k]=$(k).value.trim());persist();renderLogoPreview()};
$('logoFile').onchange=e=>{const file=e.target.files?.[0];if(!file)return;if(file.size>1024*1024){toast('Логотип слишком большой. Выбери файл до 1 МБ.');e.target.value='';return}const reader=new FileReader();reader.onload=()=>{data.logo=reader.result;persist();renderLogoPreview()};reader.readAsDataURL(file)};
$('removeLogo').onclick=()=>{data.logo='';persist();renderLogoPreview();$('logoFile').value=''};
$('addService').onclick=()=>{data.services.push({id:Date.now(),name:'Новая услуга',desc:'Описание услуги',price:1500});persist();renderServices()};
$('serviceEditor').addEventListener('input',e=>{const row=e.target.closest('.service-row');if(!row)return;const s=data.services.find(x=>x.id==row.dataset.id);if(!s)return;if(e.target.classList.contains('s-name'))s.name=e.target.value;if(e.target.classList.contains('s-desc'))s.desc=e.target.value;if(e.target.classList.contains('s-price'))s.price=Number(e.target.value)||0;localStorage.setItem(key,JSON.stringify(data))});
$('clearBookings').onclick=()=>{if(confirm('Удалить все заявки?')){localStorage.removeItem('noirBookings');renderBookings();toast('Заявки очищены')}};$('reset').onclick=()=>{if(confirm('Вернуть демо-данные?')){localStorage.removeItem(key);data=get();renderContent();renderServices();toast('Демо-данные восстановлены')}};
document.querySelectorAll('.tab').forEach(t=>t.onclick=()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.panel').forEach(x=>x.classList.remove('active'));t.classList.add('active');$(t.dataset.tab).classList.add('active');if(t.dataset.tab==='bookings')renderBookings()});renderContent();renderServices();renderBookings();
