const defaultData={brand:'NOIR',logo:'',heroText:'Не просто стрижка. Чёткая форма, чистая линия и городской характер.',spaceText:'Тёмное пространство, металл, зеркала и свет, который подчёркивает форму. Никакой случайности — только характер.',footerText:'Barber shop for people who care about the details.',address:'ул. Стильная, 14',phone:'+7 900 000 00 00',services:[
{id:1,name:'Мужская стрижка',desc:'Ножницы + машинка, мойка и финальная укладка.',price:1800},{id:2,name:'Стрижка под машинку',desc:'Чистая короткая форма без лишнего.',price:1200},{id:3,name:'Fade / Taper',desc:'Плавный переход, контур и укладка.',price:2000},{id:4,name:'Борода',desc:'Моделирование, горячее полотенце и уход.',price:1100},{id:5,name:'Стрижка + борода',desc:'Полный образ в одном визите.',price:2700},{id:6,name:'Камуфляж седины',desc:'Мягкое тонирование без эффекта окрашивания.',price:1500}]};
const storeKey='noirBarberData';
function getData(){try{return {...defaultData,...(JSON.parse(localStorage.getItem(storeKey))||{})}}catch{return structuredClone(defaultData)}}
function escapeHtml(s){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#039;','"':'&quot;'}[c]))}
const data=getData();
document.querySelectorAll('[data-bind]').forEach(el=>{const key=el.dataset.bind;if(data[key]!=null)el.textContent=data[key]});
function renderLogo(){document.querySelectorAll('[data-logo]').forEach(el=>{el.innerHTML=data.logo?`<img src="${escapeHtml(data.logo)}" alt="${escapeHtml(data.brand||'Logo')}">`:`<span data-bind="brand">${escapeHtml(data.brand||'NOIR')}</span>`});document.querySelectorAll('[data-logo-mark]').forEach(el=>{el.textContent=(data.brand||'N').trim().charAt(0).toUpperCase()||'N'})}
renderLogo();
const grid=document.getElementById('serviceGrid');const select=document.getElementById('bookingService');
if(grid){grid.innerHTML=data.services.map((s,i)=>`<a class="service-card" href="#booking" data-service="${s.id}"><span class="service-no">${String(i+1).padStart(2,'0')}</span><div><h3>${escapeHtml(s.name)}</h3><p>${escapeHtml(s.desc)}</p></div><span class="price">${Number(s.price).toLocaleString('ru-RU')} ₽</span></a>`).join('')}
if(select){select.innerHTML='<option value="">Выбрать услугу</option>'+data.services.map(s=>`<option value="${s.id}">${escapeHtml(s.name)} — ${Number(s.price).toLocaleString('ru-RU')} ₽</option>`).join('')}
document.querySelectorAll('.service-card').forEach(card=>card.addEventListener('click',()=>{if(select)select.value=card.dataset.service}));
const menuBtn=document.getElementById('menuBtn'),mobileMenu=document.getElementById('mobileMenu');menuBtn?.addEventListener('click',()=>mobileMenu.classList.toggle('open'));mobileMenu?.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>mobileMenu.classList.remove('open')));
const date=document.getElementById('bookingDate');if(date)date.min=new Date().toISOString().slice(0,10);
const toast=document.getElementById('toast');function showToast(msg){toast.textContent=msg;toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),4200)}
document.getElementById('bookingForm')?.addEventListener('submit',e=>{e.preventDefault();const f=new FormData(e.target);const bookings=JSON.parse(localStorage.getItem('noirBookings')||'[]');bookings.unshift({id:Date.now(),created:new Date().toISOString(),name:f.get('name'),phone:f.get('phone'),serviceId:f.get('service'),date:f.get('date'),time:f.get('time'),comment:f.get('comment'),status:'new'});localStorage.setItem('noirBookings',JSON.stringify(bookings));e.target.reset();showToast('Заявка отправлена. Владелец увидит её в панели.');window.location.hash='booking'});
const progress=document.getElementById('pageProgress');window.addEventListener('scroll',()=>{const h=document.documentElement.scrollHeight-innerHeight;progress.style.width=(h>0?(scrollY/h)*100:0)+'%'});
const reveals=document.querySelectorAll('.reveal');if('IntersectionObserver' in window){const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('is-visible');io.unobserve(e.target)}}),{threshold:.12});reveals.forEach(el=>io.observe(el))}else reveals.forEach(el=>el.classList.add('is-visible'));
if(matchMedia('(min-width:901px)').matches){const dot=document.getElementById('cursorDot'),ring=document.getElementById('cursorRing');let mx=innerWidth/2,my=innerHeight/2,rx=mx,ry=my;window.addEventListener('mousemove',e=>{mx=e.clientX;my=e.clientY;dot.style.left=mx+'px';dot.style.top=my+'px'});function tick(){rx+=(mx-rx)*.18;ry+=(my-ry)*.18;ring.style.left=rx+'px';ring.style.top=ry+'px';requestAnimationFrame(tick)}tick();document.querySelectorAll('a,button,.magnetic-card,.field input,.field select').forEach(el=>{el.addEventListener('mouseenter',()=>ring.classList.add('hover'));el.addEventListener('mouseleave',()=>ring.classList.remove('hover'))});document.querySelectorAll('.magnetic').forEach(el=>{el.addEventListener('mousemove',e=>{const r=el.getBoundingClientRect();el.style.transform=`translate(${(e.clientX-r.left-r.width/2)*.08}px,${(e.clientY-r.top-r.height/2)*.08}px)`});el.addEventListener('mouseleave',()=>el.style.transform='')});document.querySelectorAll('.magnetic-card').forEach(card=>{card.addEventListener('mousemove',e=>{const r=card.getBoundingClientRect(),x=(e.clientX-r.left)/r.width-.5,y=(e.clientY-r.top)/r.height-.5;card.style.transform=`perspective(900px) rotateX(${y*-3}deg) rotateY(${x*4}deg) translateY(-4px)`});card.addEventListener('mouseleave',()=>card.style.transform='')})}
